version: '2'

services:
  jhipster-mysql:
    image: mysql:5.7.30
    volumes:
      - ../mysql_data:/var/lib/mysql/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    healthcheck:
      test: [ "CMD", "mysql -uroot", "-psecret", "-e", "SELECT 1" ]

 uaa-app:
   image: uaa
   environment:
     - _JAVA_OPTIONS=-Xmx512m -Xms256m
     - SPRING_PROFILES_ACTIVE=prod,swagger
     - SPRING_DATASOURCE_URL=jdbc:mysql://jhipster-mysql:3306/uaa?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
     - JHIPSTER_SLEEP=30

 demo1-app:
   image: demo1
   environment:
     - _JAVA_OPTIONS=-Xmx512m -Xms256m
     - SPRING_PROFILES_ACTIVE=prod,swagger
     - SPRING_DATASOURCE_URL=jdbc:mysql://jhipster-mysql:3306/demo1?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
     - JHIPSTER_SLEEP=30

 demo2-app:
   image: demo2
   environment:
     - _JAVA_OPTIONS=-Xmx512m -Xms256m
     - SPRING_PROFILES_ACTIVE=prod,swagger
     - SPRING_DATASOURCE_URL=jdbc:mysql://jhipster-mysql:3306/demo2?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
     - JHIPSTER_SLEEP=30
