# API-first development with OpenAPI
# This file will be used at compile time to generate Spring-MVC endpoint stubs using openapi-generator
openapi: '3.0.1'

info:
  title: 'demo2'
  version: 0.0.1

servers:
  - url: http://localhost:8082/api
    description: Development server
  - url: https://localhost:8082/api
    description: Development server with TLS Profile

paths:
  /demo2:
    get:
      tags:
        - Demo2
      operationId: demo2
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringValue'

components:
  schemas:
    StringValue:
      type: string

  responses:
    Problem:
      description: error occurred - see status code and problem object for more information.
      content:
        'application/problem+json':
          schema:
            $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
